development:
  adapter: postgresql
  encoding: SQL_ASCII
  database: postgres
  pool: 5
  username: ubuntu
  password: password

test:
  adapter: postgresql
  encoding: SQL_ASCII
  database: postgres
  pool: 5
  username: ubuntu
  password: password